#!/bin/zsh

echo "Have you saved changes? Save them now then enter then enter any character"
read resp
echo "Enter branch name: "
read branchname
echo "Performing git checkout with $branchname"
git checkout -b $branchname
git add .
echo "FILES ADDED"
git status
echo "Enter commit message: "
read message
echo "COMMITTING"
git commit -m "$message"
echo "PUSHING"
git push origin $branchname
git checkout master
git pull 